apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  labels:
    app: neo4j
data:
  NEO4J_AUTH: "neo4j/W-%A8ya?N-z+s=-"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pv-claim
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Service
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  type: NodePort
  ports:
    - port: 7474
    - port: 7687
  selector:
    app: neo4j

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:5.18-community-bullseye
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            exec:
              command: ["wget", "--no-verbose", "--tries=1", "--spider", "localhost:7474", "||", "exit", "1"]
            failureThreshold: 4
            periodSeconds: 20
            timeoutSeconds: 5
            initialDelaySeconds: 30
          ports:
            - containerPort: 7474
            - containerPort: 7687
          envFrom:
            - configMapRef:
                name: neo4j-config
          volumeMounts:
            - mountPath: /var/lib/neo4j/data
              name: neo4jdb
      volumes:
        - name: neo4jdb
          persistentVolumeClaim:
            claimName: neo4j-pv-claim