service_name = 'frontend'
configurations = ['k8s.yml']
ports=['82:80']

docker_build(
    ref='wuuu/frontend-nuxt',
    context='.',
)

k8s_yaml(configurations)

k8s_resource(service_name, port_forwards=ports)
