service_name = 'frontend'
configurations = ['nginx/k8s.yml']

local('pnpm run build')

docker_build(
    ref='wuuu/frontend-nginx',
    context='.',
    live_update = [
        sync('./dist', '/usr/share/nginx/html'),
    ]
)

k8s_yaml(configurations)

k8s_resource(service_name, port_forwards=['80:80'])
