apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
        - name: backend-service
          image: wuuu/backend-service:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          lifecycle:
            preStop:
              exec:
                command: [ "CMD", "curl", "-f", "http://127.0.0.1:8080/actuator/health" ]
          ports:
            - containerPort: 8080
              hostPort: 8082
          resources:
            requests:
              cpu: "0.2"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"