module_name = 'backend'
image_name = 'wuuu/backend'
service_name = 'backend-service'
ports = ['8082:8080']
configurations = ['k8s.yml']

gradlew = "./gradlew"
ref_placeholder = "$EXPECTED_REF"

if os.name == "nt":
    gradlew = "gradlew.bat"
    ref_placeholder = "%EXPECTED_REF%"

custom_build(
    ref=image_name,
    command=gradlew + ' :' + module_name + ':jibDockerBuild --image ' + ref_placeholder,
    deps=[module_name + '/build/classes', module_name + '/src', module_name + '/build.gradle', 'build.gradle'],
    entrypoint='java -noverify -cp /app/resources:/app/classes:/app/libs/* $(cat /app/jib-main-class-file)',
    dir='../'
)

k8s_yaml(configurations)

k8s_resource(service_name, port_forwards=ports)
