apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: wuuu/auth
          imagePullPolicy: "IfNotPresent"
          securityContext:
            runAsUser: 1001
          lifecycle:
            preStop:
              httpGet:
                port: 8080
                path: /actuator/health
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "0.2"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"