apiVersion: v1
kind: Service
metadata:
  name: router
  labels:
    app: router
spec:
  type: ClusterIP
  selector:
    app: graphql-gateway
  ports:
    - port: 80
      targetPort: 9991

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  labels:
    app: graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      containers:
        - name: graphql-gateway
          image: wuuu/graphql-gateway
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              cpu: "0.2"
              memory: "512M"
            limits:
              cpu: "1"
              memory: "512M"
          ports:
            - containerPort: 9991
