service_name = 'graphql-gateway'
configurations = ['k8s.yml']
ports = ['800:9991']

docker_build(
    ref='wuuu/graphql-gateway',
    context='.',
    build_args = {
        'public_node_url': 'http://localhost/api',
    },
)

k8s_yaml(configurations)

k8s_resource(service_name, port_forwards=ports)
