apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: "80"
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: wuuu/frontend:latest
          imagePullPolicy: "IfNotPresent"
          livenessProbe:
            httpGet:
              port: 80
              path: /
            failureThreshold: 10
            periodSeconds: 20
            timeoutSeconds: 5
            initialDelaySeconds: 60
          name: frontend
          ports:
            - containerPort: 80
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: "200M"
      restartPolicy: Always
